// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogeyepzuunxbsilepvqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nZXllcHp1dW54YnNpbGVwdnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODY0MzksImV4cCI6MjA3MjU2MjQzOX0.Zgq_qHQDs3631wkXrXdW-nielb-dDF0akkHhSdkE9qA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});